language: java
dist: trusty
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
before_deploy:
- mvn package assembly:single
deploy:
  provider: releases
  api_key: $DEPLOYMENT_KEY
  file: target/tecajnica-$TRAVIS_TAG.jar
  on:
    tags: true
    repo: Glusk/tecajnica
    condition: $TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$ # Only deploy tags that match something like 1.0.0
  skip_cleanup: 'true'
